title: modusapps.com
default_lang: en
author:
  name: 'ModusApps Team'
  email: kris@moosequest.net
taxonomies:
  - mobile
  - apps
metadata:
  description: 'modusapps enable you to use different modes of transit to better our planet.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
