version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1457353897
layout:
  /top/:
    -
      - system-messages-9828
  /navigation/:
    -
      - 'logo-5992 17'
      - 'social-7220 13'
      - 'menu-4196 70'
  /header/:
    -
      - 'position-position-7051 50'
      - 'position-position-2504 50'
  /slideshow/:
    -
      - position-position-6661
  /above/:
    -
      - position-position-3264
  /showcase/:
    -
      - position-position-9435
    -
      - position-position-8620
    -
      - position-position-3083
  /utility/:
    -
      - position-position-5239
  /feature/:
    -
      - position-position-7980
  /container-4448/:
    -
      -
        'sidebar 20':
          -
            - position-position-8538
      -
        'mainbar 60':
          -
            - position-position-8547
          -
            - system-content-1120
      -
        'aside 20':
          -
            - position-position-8807
  /expanded/:
    -
      - 'position-position-8124 50'
      - 'position-position-8346 50'
  /extension/:
    -
      - position-position-4800
  /bottom/:
    -
      - position-position-3343
  /footer/:
    -
      - 'position-position-6548 60'
      - 'position-position-2750 40'
  /copyright/:
    -
      - copyright-5748
  offcanvas:
    -
      - mobile-menu-7951
structure:
  top:
    type: section
    attributes:
      boxed: '0'
  navigation:
    type: section
    attributes:
      boxed: '0'
      class: ''
  header:
    attributes:
      boxed: '0'
      class: ''
  slideshow:
    type: section
    attributes:
      boxed: '0'
      class: ''
  above:
    type: section
    attributes:
      boxed: '0'
      class: ''
  showcase:
    type: section
    attributes:
      boxed: '0'
      class: ''
  utility:
    type: section
    attributes:
      boxed: '0'
      class: ''
  feature:
    type: section
    attributes:
      boxed: '0'
      class: ''
  sidebar:
    type: section
    block:
      class: equal-height
  mainbar:
    type: section
    block:
      class: equal-height
  aside:
    block:
      class: equal-height
  container-4448:
    attributes:
      boxed: '0'
      class: ''
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: '0'
      class: ''
  extension:
    type: section
    attributes:
      boxed: '0'
      class: ''
  bottom:
    type: section
    attributes:
      boxed: '0'
      class: ''
  footer:
    attributes:
      boxed: '0'
      class: ''
  copyright:
    type: section
    attributes:
      boxed: '0'
      class: g-mobile-center-compact
content:
  logo-5992:
  social-7220:
    attributes:
      css:
        class: ''
    block:
      class:
      variations: align-left
  menu-4196:
    block:
      variations: align-right
  position-position-7051:
    title: 'Header A'
    attributes:
      key: header-a
  position-position-2504:
    title: 'Module Position'
    attributes:
      key: header-b
  position-position-6661:
    title: 'Slideshow A'
    attributes:
      key: slideshow-a
  position-position-3264:
    title: 'Above A'
    attributes:
      key: above-a
    block:
      variations: center
  position-position-9435:
    title: 'Showcase A'
    attributes:
      key: showcase-a
  position-position-8620:
    title: 'Showcase B'
    attributes:
      key: showcase-b
  position-position-3083:
    title: 'Showcase C'
    attributes:
      key: showcase-c
  position-position-5239:
    title: 'Utility A'
    attributes:
      key: utility-a
  position-position-7980:
    title: 'Feature A'
    attributes:
      key: feature-a
  position-position-8538:
    title: 'Sidebar A'
    attributes:
      key: sidebar-a
  position-position-8547:
    title: 'MainBar A'
    attributes:
      key: mainbar-a
  position-position-8807:
    title: 'Aside A'
    attributes:
      key: aside-a
  position-position-8124:
    title: 'Expanded A'
    attributes:
      key: expanded-a
  position-position-8346:
    title: 'Module Position'
    attributes:
      key: expanded-b
  position-position-4800:
    title: 'Extension A'
    attributes:
      key: extension-a
  position-position-3343:
    title: 'Bottom A'
    attributes:
      key: bottom-a
  position-position-6548:
    title: 'Module Position'
    attributes:
      key: footer-a
  position-position-2750:
    title: 'Module Position'
    attributes:
      key: footer-b
  copyright-5748:
    block:
      class: g-copyright
  mobile-menu-7951:
    title: 'Mobile Menu'
